name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v5
        id: goreleaser
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
      # extract version resolved by goreleaser
      - run: echo "VERSION=${{ fromJSON(steps.goreleaser.outputs.metadata).version }}" >> "$GITHUB_ENV"

      - run: sudo snap install --classic snapcraft

      # SNAPS
      # Creating snaps through goreleaser action isn't possible because snapcraft isn't installed,
      # but it's simple enough to hand jam here, easier than creating a custom image with goreleaser and snapcraft installed.

      ## amd64
      - run: mkdir -p /tmp/retry_${VERSION}_linux_amd64/prime/meta
      - run: ARCH=amd64 envsubst <./snap.yml.tmpl > /tmp/retry_${VERSION}_linux_amd64/prime/meta/snap.yaml
      # amd64 has _1 suffix on the binary
      - run: cp -v ./dist/retry_linux_amd64_v1/retry /tmp/retry_${VERSION}_linux_amd64/prime/retry
      - run: snapcraft pack /tmp/retry_${VERSION}_linux_amd64/prime --output /tmp/retry_${VERSION}_linux_amd64.snap

      ## arm64
      - run: mkdir -p /tmp/retry_${VERSION}_linux_arm64/prime/meta
      - run: ARCH=arm64 envsubst <./snap.yml.tmpl > /tmp/retry_${VERSION}_linux_arm64/prime/meta/snap.yaml
      # arm64 doesn't have the _1 suffix on the binary, unlike amd64
      - run: cp -v ./dist/retry_linux_arm64/retry /tmp/retry_${VERSION}_linux_arm64/prime/retry
      - run: snapcraft pack /tmp/retry_${VERSION}_linux_arm64/prime --output /tmp/retry_${VERSION}_linux_arm64.snap

      - name: upload snaps to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/retry_${{env.VERSION}}_linux_arm64.snap
            /tmp/retry_${{env.VERSION}}_linux_amd64.snap
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_LOGIN }}
        with:
          snap: /tmp/retry_${{env.VERSION}}_linux_arm64.snap
          release: edge
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_LOGIN }}
        with:
          snap: /tmp/retry_${{env.VERSION}}_linux_amd64.snap
          release: edge
